language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pear25/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pear25/react-test npm run test

after_success:
  - docker build -t pear25/multi-client ./client
  - docker build -t pear25/multi-server ./server
  - docker build -t pear25/multi-worker ./worker
  - docker build -t pear25/multi-nginx ./nginx
  - docker login -u "$docker_id" -p "$docker_password"
  - docker push pear25/multi-client
  - docker push pear25/multi-server
  - docker push pear25/multi-worker
  - docker push pear25/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-611087197763'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

